### ISSUE TITLE
Content Pages

### ISSUE THREAD

**Issue by haydennyyy** [playroles/website#1]
## Description
Currently, there are no pages for content. They need to be connected to the API and fetched using Next.js and the `fetch` API.

## Roadmap
- [ ] Lore
  - [x] Group Index (Deployed! ✨ https://playroles.now.sh/lore)
  - [x] Wiki-like layout (Deployed! ✨ https://playroles.now.sh/lore/aria-ceta#noble-phantasms_mjolnir)
  - [ ] CRUD
- [ ] Characters
  - [x] Index (Deployed! ✨ https://playroles.now.sh/characters)
  - [ ] CRUD
- [ ] Users
  - [x] Index (Deployed! ✨ https://playroles.now.sh/users)
  - [ ] CRUD
  - [ ] Followers, posts

**Comment by haydennyyy** [comment]
Characters page deployed.

**Comment by haydennyyy** [comment]
Users page deployed.
